on:
  - pull_request
  - pull_request_target
  - push
jobs:
  hello:
    runs-on: ubuntu-slim
    steps:
    - shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        TARGET_ENV: ${{ vars.TARGET_ENVIRONMENT }}
      run: |
        echo "Hello"
        echo "Event Name: ${EVENT_NAME}"
        echo "target env: ${TARGET_ENV}"